# Neural Networks from Scratch

Using a neural net to recognize handwritten digits.

## Perceptrons

A perceptron is a type of neuron which in no longer in use by modern neural netwoks. Modern neural networks use sigmoid neurons. A perceptron takes several binary inputs and produces a single binary output. To compute the output of a perceptron the perceptron introduces weights (w), real numbers expressing the importance of the respective input to the output. The output of the perceptron depends on whether the weighted sum of the input and weights is greater than a threshold.

## Sigmoid Neurons

The goal is to change the values of the weights and biases by a small amount so that the output of the network also changes by a small amount. This isn't possible with perceptrons since a small change in the value of a bias or weight of a perceptron can cause the perceptron to flip from one value to the other for example from 0 to 1 which would cause the rest of the network to change the behaviour compleately. This can be overcome by the introduction of the Sigmoid neuron which is similar to the perceptron but the difference is that it accepts inputs other than 0s and 1s and the output is not just the weigted sum of the inputs and bias but it is inserted into the sigmoid function which is defined by:

\begin{equation}
\sigma(z) = \frac{1}{1 + e^{-z}}
\end{equation}

This just means that if z is a large positive number than the output of the sigmoid neuron is close to 1, and if it is very negative then it is close to 0, but when it is a modes size number it will give a number in between 0 and 1 which is different from the perceptron.

In [1]:
import numpy as np

In [2]:
import random
import numpy as np

class Network(object):

    def __init__(self, sizes):
        self.num_layers = len(sizes)
        self.sizes = sizes
        self.biases = [np.random.randn(y, 1) for y in sizes[1:]]
        self.weights = [np.random.randn(y, x) for x, y in zip(sizes[:-1], sizes[1:])]

    def feedforward(self, a):
        for b, w in zip(self.biases, self.weights):
            a = sigmoid(np.dot(w, a)+b)
        return a

    def SGD(self, training_data, epochs, mini_batch_size, eta, test_data=None):
        if test_data: n_test = len(test_data)
        n = len(training_data)
        for j in range(epochs):
            random.shuffle(training_data)
            mini_batches = [training_data[k:k+mini_batch_size] for k in range(0, n, mini_batch_size)]
            for mini_batch in mini_batches:
                self.update_mini_batch(mini_batch, eta)
            if test_data:
                print("Epoch {0}: {1} / {2}".format(j, self.evaluate(test_data), n_test))
            else:
                print("Epoch {0} complete".format(j))

    def update_mini_batch(self, mini_batch, eta):
        nabla_b = [np.zeros(b.shape) for b in self.biases]
        nabla_w = [np.zeros(w.shape) for w in self.weights]
        for x, y in mini_batch:
            delta_nabla_b, delta_nabla_w = self.backprop(x, y)
            nabla_b = [nb+dnb for nb, dnb in zip(nabla_b, delta_nabla_b)]
            nabla_w = [nw+dnw for nw, dnw in zip(nabla_w, delta_nabla_w)]
        self.weights = [w-(eta/len(mini_batch))*nw for w, nw in zip(self.weights, nabla_w)]
        self.biases = [b-(eta/len(mini_batch))*nb for b, nb in zip(self.biases, nabla_b)]

    def backprop(self, x, y):
        nabla_b = [np.zeros(b.shape) for b in self.biases]
        nabla_w = [np.zeros(w.shape) for w in self.weights]
        activation = x
        activations = [x]
        zs = []
        for b, w in zip(self.biases, self.weights):
            z = np.dot(w, activation)+b
            zs.append(z)
            activation = sigmoid(z)
            activations.append(activation)
        delta = self.cost_derivative(activations[-1], y) * \
            sigmoid_prime(zs[-1])
        nabla_b[-1] = delta
        nabla_w[-1] = np.dot(delta, activations[-2].transpose())
        for l in range(2, self.num_layers):
            z = zs[-l]
            sp = sigmoid_prime(z)
            delta = np.dot(self.weights[-l+1].transpose(), delta) * sp
            nabla_b[-l] = delta
            nabla_w[-l] = np.dot(delta, activations[-l-1].transpose())
        return (nabla_b, nabla_w)

    def evaluate(self, test_data):
        test_results = [(np.argmax(self.feedforward(x)), y) for (x, y) in test_data]
        return sum(int(x == y) for (x, y) in test_results)

    def cost_derivative(self, output_activations, y):
        return (output_activations-y)

def sigmoid(z):
    return 1.0/(1.0+np.exp(-z))

def sigmoid_prime(z):
    return sigmoid(z)*(1-sigmoid(z))

In [3]:
from tensorflow.keras.datasets import mnist

def load_data():
    (x_train, y_train), (x_test, y_test) = mnist.load_data()

    split_index = 50000
    x_train, x_val = x_train[:split_index], x_train[split_index:]
    y_train, y_val = y_train[:split_index], y_train[split_index:]

    training_data = (x_train.reshape(50000, 784).astype('float32') / 255, y_train.astype('int32'))
    validation_data = (x_val.reshape(10000, 784).astype('float32') / 255, y_val.astype('int32'))
    test_data = (x_test.reshape(10000, 784).astype('float32') / 255, y_test.astype('int32'))
    
    return (training_data, validation_data, test_data)

def load_data_wrapper():
    tr_d, va_d, te_d = load_data()

    training_inputs = [np.reshape(x, (784, 1)) for x in tr_d[0]]
    training_results = [vectorized_result(y) for y in tr_d[1]]
    training_data = list(zip(training_inputs, training_results))

    validation_inputs = [np.reshape(x, (784, 1)) for x in va_d[0]]
    validation_data = list(zip(validation_inputs, va_d[1]))

    test_inputs = [np.reshape(x, (784, 1)) for x in te_d[0]]
    test_data = list(zip(test_inputs, te_d[1]))
    
    return (training_data, validation_data, test_data)

def vectorized_result(j):
    e = np.zeros((10, 1))
    e[j] = 1.0
    return e

2026-01-28 17:15:32.295732: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1769616932.315683 1245427 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1769616932.321510 1245427 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1769616932.335707 1245427 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1769616932.335725 1245427 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1769616932.335727 1245427 computation_placer.cc:177] computation placer alr

In [4]:
net = Network([784,30,10])

In [5]:
training_data, validation_data, test_data = load_data_wrapper()

In [6]:
#net.SGD(training_data, 30, 10, 3.0,test_data=test_data)

## Basics

Matrix Math

Creating a numpy array with random values

In [7]:
W = np.random.randn(2,3)
W

array([[-2.17565183,  2.2839055 ,  0.39693841],
       [-0.87064199, -0.23982708,  0.75004924]])

Creating two numpy arrays and calculating the product

In [8]:
a1 = np.array([[2,1],[3,4]])
a1

array([[2, 1],
       [3, 4]])

In [9]:
a2 = np.array([[3,5],[1,1]])
a2

array([[3, 5],
       [1, 1]])

In [10]:
a3 = a1*a2
a3

array([[6, 5],
       [3, 4]])

Using the sum function on a numpy array

In [11]:
aw = sum(a3)
aw

array([9, 9])

### Simple nerual network with only input layer and output layer

Calculating z value (z = x1*w1 + x2*w2 + ... + xnWn + b) of a neural network which has only 3 neurons in the input layer and only one neuron in the output layer with no hidden layers

First create an input X

In [12]:
X = np.random.rand(1,3)

In [13]:
X

array([[0.51784897, 0.79380949, 0.60988485]])

In [14]:
X = X.T
X

array([[0.51784897],
       [0.79380949],
       [0.60988485]])

Create weights for the network

In [15]:
W = np.random.rand(3,1)
W

array([[0.19647827],
       [0.48147246],
       [0.14269355]])

Creating the bias for the network (neuron)

In [16]:
B = np.array([[1]])
B

array([[1]])

In [17]:
X * W

array([[0.10174607],
       [0.38219741],
       [0.08702663]])

In [18]:
z = np.dot(X.T,W) + B
z

array([[1.57097011]])

Creating the activation function (sigmoid)

In [19]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [20]:
activation = sigmoid(z)
activation

array([[0.82792186]])

Creating the cost function

In [21]:
def cost_function(y, a):
    return 1/2 * (y-a)**2

Let's say the output was supposed to be 0

In [22]:
y = 0

In [23]:
cost_function(y, activation)

array([[0.3427273]])

Now we want to see how the cost function changes if we change the weights

In [24]:
def changes_in_weights(a, y, X):
    return (a-y)*a*(1-a)*X

In [25]:
changes_in_weights(activation, y, X)

array([[0.06108119],
       [0.09363122],
       [0.07193699]])

Now we want to see how the cost function changes if we change the bias

In [26]:
def changes_in_bias(a, y):
    return (a-y)*a*(1-a)

In [27]:
changes_in_bias(activation, y)

array([[0.11795175]])

In [28]:
gradient_of_cost_function = np.vstack((changes_in_weights(activation, y, X),changes_in_bias(activation, y)))
gradient_of_cost_function

array([[0.06108119],
       [0.09363122],
       [0.07193699],
       [0.11795175]])

In [29]:
parameters = np.vstack((W,B))
parameters

array([[0.19647827],
       [0.48147246],
       [0.14269355],
       [1.        ]])

In [30]:
lr = 0.01

In [31]:
new_parameters = parameters - lr*(gradient_of_cost_function)
new_parameters

array([[0.19586746],
       [0.48053615],
       [0.14197418],
       [0.99882048]])

In [32]:
new_parameters[3:]

array([[0.99882048]])

Combining everything into one fucntion

In [33]:
W.shape[0]

3

In [34]:
def setting_weights_biases(new_parameters):
    weights = new_parameters[0:W.shape[0]]
    biases = new_parameters[W.shape[0]]
    return weights, biases

In [35]:
weights = setting_weights_biases(new_parameters)[0]
weights

array([[0.19586746],
       [0.48053615],
       [0.14197418]])

In [36]:
biases = setting_weights_biases(new_parameters)[1]
biases

array([0.99882048])

In [37]:
def calculate_cost(X,W,B,y):
    z = np.dot(X.T,W) + B
    activation = sigmoid(z)
    return cost_function(y, activation)

Old cost before changing the parameters

In [38]:
calculate_cost(X,W,B,y)

array([[0.3427273]])

New cost after changing the parameters

In [39]:
calculate_cost(X,weights,biases,y)

array([[0.34241125]])

Backpropagation

### Making the structure more complicated

Defining functions

In [40]:
def cost_function(y, a):
    return 1/2 * (y-a)**2

In [41]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [42]:
def calculate_activations(activations, weights, biase):
    return sigmoid(np.dot(activations, weights) + biase)

Defining the structure of the neural network as an array of neurons per layer

In [43]:
neural_network_structure = [2,3,2,3]

Creating a random input matrix

In [44]:
X = np.random.rand(1,2)

Creating a y

In [60]:
y = np.array([[0,1,0]])

Forward propagation

In [46]:
w1 = np.random.rand(2,3)
w1

array([[0.19276842, 0.01347352, 0.67264644],
       [0.97645356, 0.42972494, 0.8428079 ]])

In [47]:
b1 = np.random.rand(1,3)

In [48]:
layer1_activations = calculate_activations(X,w1,b1)

In [49]:
w2 = np.random.rand(3,2)
w2

array([[0.44085494, 0.02338824],
       [0.19937845, 0.8041704 ],
       [0.36367039, 0.26818733]])

In [50]:
b2 = np.random.rand(1,2)
b2

array([[0.2920343 , 0.18460198]])

In [51]:
layer2_activations = calculate_activations(layer1_activations,w2,b2)
layer2_activations

array([[0.72737388, 0.70455998]])

In [52]:
w3 = np.random.rand(2,3)
w3

array([[0.37552718, 0.68698446, 0.7565467 ],
       [0.15219199, 0.929787  , 0.97262259]])

In [53]:
b3 = np.random.rand(1,3)
b3

array([[0.41597851, 0.98517659, 0.97465366]])

In [54]:
layer3_activations = calculate_activations(layer2_activations,w3,b3)
layer3_activations

array([[0.68919436, 0.89472702, 0.90116325]])

Calculating the cost function

In [55]:
cf = cost_function(y,layer3_activations)
cf

array([[0.23749443, 0.0055412 , 0.4060476 ]])

Backpropagation

In [61]:
def changes_in_weights(a, y, X):
    return np.dot(X.T,(a-y)*a*(1-a))

In [63]:
last_layer_weights = changes_in_weights(layer3_activations,y,layer2_activations)

In [64]:
last_layer_weights

array([[ 0.10738164, -0.00721244,  0.05838256],
       [ 0.10401364, -0.00698622,  0.0565514 ]])

In [65]:
second_layer_weights = np.dot(last_layer_weights,w3.T) * layer2_activations * (1 - layer2_activations)

In [66]:
second_layer_weights

array([[0.01577268, 0.01382583],
       [0.01527797, 0.01339219]])

In [67]:
first_layer_weights = np.dot(second_layer_weights,w2.T) * layer1_activations * (1 - layer1_activations)

In [68]:
first_layer_weights

array([[0.00151612, 0.00344668, 0.0019135 ],
       [0.00146857, 0.00333857, 0.00185348]])

#### Fitting it all together

Setting up the weights and biases

In [69]:
neural_network_structure = [2,3,2,3]

In [144]:
def set_weights(neural_network_structure):
    #weights = [np.random.rand(x,y) for x,y in 
    w1 = np.random.rand(2,3)
    w2 = np.random.rand(3,2)
    w3 = np.random.rand(2,3)
    weights = [w1,w2,w3]
    return weights

In [145]:
def set_biases(neural_network_structure):
    return [np.random.rand(1,x) for x in neural_network_structure[1:]]

In [146]:
biases = set_biases(neural_network_structure)
biases[0]

array([[0.53306084, 0.68568827, 0.42807228]])

In [147]:
weights = set_weights(neural_network_structure)
weights

[array([[0.03005338, 0.72407003, 0.79301445],
        [0.36099523, 0.5534999 , 0.06355963]]),
 array([[0.21463591, 0.09284456],
        [0.18307065, 0.39722362],
        [0.78741107, 0.59817996]]),
 array([[0.67165231, 0.8845512 , 0.26075705],
        [0.4391401 , 0.97928358, 0.51177291]])]

In [155]:
def forward_pass(X,weights,biases):
    z_values = []
    activations = [X]
    for layer in range(len(neural_network_structure[:-1])):
            z_values.append(np.dot(activations[layer],weights[layer]) + biases[layer])
            activations.append(sigmoid(z_values[layer]))
    return z_values, activations

In [156]:
z_values, activations = forward_pass(X,weights,biases)

In [157]:
z_values

[array([[0.60312154, 1.20010027, 0.91326978]]),
 array([[0.92985111, 1.54072771]]),
 array([[1.63526596, 1.79743694, 1.37499799]])]

In [158]:
activations

[array([[0.60028977, 0.14410151]]),
 array([[0.64637014, 0.76854262, 0.71366879]]),
 array([[0.71704508, 0.82357049]]),
 array([[0.83688975, 0.85783665, 0.79818645]])]

In [179]:
def backprop(activations,Y,weights):
    errors = [None] * (len(activations) - 1)
    errors[-1] = (activations[-1]-Y)*(activations[-1]*(1-activations[-1]))
    for l in reversed(range(len(errors)-1)):
        errors[l] = np.dot(errors[l+1],weights[l+1].T) * (activations[l+1] * (1-activations[l+1]))
    return errors

In [180]:
Y = np.array([[1,0,0]])

In [181]:
backprop(activations,Y,weights)

[array([[0.00159466, 0.00236118, 0.00644195]]),
 array([[0.02254334, 0.02302637]]),
 array([[-0.02226541,  0.1046157 ,  0.12857574]])]

In [182]:
break

SyntaxError: 'break' outside loop (668683560.py, line 1)

## Mnist 

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv('Data/minist_train.csv')

In [ ]:
data.head()

In [ ]:
data.shape

In [ ]:
data = np.array(data)
m, n = data.shape
np.random.shuffle(data)

In [ ]:
val_data = data[0:1000].T
Y_val = val_data[0]
X_val = val_data[1:n]

train_data = data[1000:m].T
Y_train = train_data[0]
X_train = train_data[1:n]

In [ ]:
X_train.shape

In [ ]:
X_train.shape[0]

In [ ]:
Y_train.max() + 1

In [ ]:
neural_network_size

In [ ]:
neural_network_size = [X_train.shape[0],4,5,10]

In [ ]:
neural_network_size[1]

In [ ]:
def init_params(neural_network_size):
    W1 = np.random.rand(X_train.shape[0],neural_network_size[1])
    W2 = np.random.rand(neural_network_size[1],neural_network_size[2])
    W3 = np.random.rand(neural_network_size[2],neural_network_size[3])
    B1 = np.random.rand(neural_network_size[1],1)
    B2 = np.random.rand(neural_network_size[2],1)
    B3 = np.random.rand(neural_network_size[3],1)
    return W1, W2, W3, B1, B2, B3

In [ ]:
init_params(neural_network_size)